# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: d892ed8c3c4d17ad18ce8781642c2429b51c372e4fd029baf9babd6e8a4a9c12e1c2d853f59e7b7bcc6025b3e73daed2bf843fe08f786ac43d86d43ba8c07fd9

test:
  secret_key_base: bda6b478e5129069dd20fcb81057571c6416329e9102cbcce53fa9b50e1e79ad3332181e68a8f1cf0b45469681c6d000982716f47f1f4c9899595dafcc141b2f

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
